/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import racetrackScene from '/assets/3d/racetrack.glb'

const RaceTrack = (props)  => {

  const { nodes, materials } = useGLTF(racetrackScene)

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 0.05, 0]}
        scale={[1.14, 0.382, 10.896]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[-19.068, -1.336, 39.707]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-145.999, -2.206, -116.28]}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[53.578, -3.023, -31.029]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[26.222, -3.023, -36.814]}
        scale={6.608}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-158.207, -4.259, -140.689]}
        rotation={[0, 1.407, 0]}
        scale={5.977}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_02_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-229.981, -4.259, -46.32]}
        scale={4.529}
      />
      <mesh
        geometry={nodes.PP_Grass_11_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[0, 0, -8.445]}
      />
      <mesh
        geometry={nodes.PP_Lake_Ground_04_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-106.628, -5.718, 137.777]}
        scale={[3.515, 3.487, 2.596]}
      />
      <mesh
        geometry={nodes.PP_Meadow_07_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-154.637, -2.472, 145.365]}
        scale={[1.127, 0.523, 1.037]}
      />
      <mesh
        geometry={nodes.PP_Meadow_Path_05_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[86.17, -3.138, -17.385]}
      />
      <mesh
        geometry={nodes.PP_Rock_Moss_Grown_09_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[49.049, -2.068, 41.244]}
        scale={5.305}
      />
      <mesh
        geometry={nodes.PP_Rock_Moss_Grown_11_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[34.885, -2.068, 37.598]}
        scale={4.265}
      />
      <mesh
        geometry={nodes.PP_Rock_Pile_Forest_Moss_05_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-45.322, -6.232, 29.973]}
        rotation={[Math.PI, -0.949, Math.PI]}
        scale={3.373}
      />
      <mesh
        geometry={nodes.PP_Rock_Pile_Forest_Moss_10_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-49.575, -6.232, 129.609]}
        rotation={[0, 1.326, 0]}
        scale={3.819}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-40.653, -3.632, 22.103]}
        rotation={[Math.PI, -0.853, Math.PI]}
        scale={4.039}
      />
      <mesh
        geometry={nodes.PP_Tree_10_001_PP_Standard_Material_0.geometry}
        material={materials.PP_Standard_Material}
        position={[-23.19, -1.605, 42.201]}
        scale={2.271}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_02_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.001']}
        position={[-204.729, 0, 174.665]}
        scale={4.568}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.002']}
        position={[-73.734, -4.259, -148.119]}
        rotation={[0, 1.407, 0]}
        scale={[4.222, 7.659, 4.222]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.003']}
        position={[-230.694, -4.259, -104.249]}
        rotation={[-0.001, 1.407, 0]}
        scale={[6.06, 7.755, 4.554]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.004']}
        position={[2.161, -4.259, -149.132]}
        rotation={[-0.001, 1.407, 0]}
        scale={[4.971, 6.944, 4.852]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0004.geometry}
        material={materials['PP_Standard_Material.005']}
        position={[144.261, -4.259, -45.174]}
        rotation={[-0.001, 1.407, 0]}
        scale={[3.742, 4.173, 3.653]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0005.geometry}
        material={materials['PP_Standard_Material.006']}
        position={[77.681, -4.259, -116.56]}
        rotation={[0, 0.132, -0.001]}
        scale={[4.677, 5.115, 4.565]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0006.geometry}
        material={materials['PP_Standard_Material.007']}
        position={[159.257, -4.259, -132.449]}
        rotation={[0, 1.407, 0]}
        scale={[4.732, 5.294, 4.509]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0007.geometry}
        material={materials['PP_Standard_Material.008']}
        position={[159.839, -4.259, 77.656]}
        rotation={[-3.14, -1.482, -3.141]}
        scale={[4.572, 4.531, 3.436]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0008.geometry}
        material={materials['PP_Standard_Material.009']}
        position={[231.643, -4.259, 65.591]}
        rotation={[-0.001, 1.407, 0]}
        scale={[5.39, 4.006, 4.05]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0009.geometry}
        material={materials['PP_Standard_Material.010']}
        position={[133.92, -4.259, 174.518]}
        rotation={[0, 0.798, -0.001]}
        scale={[4.971, 3.695, 3.736]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0010.geometry}
        material={materials['PP_Standard_Material.011']}
        position={[-227.383, -4.259, -27.539]}
        rotation={[-0.001, 1.407, 0]}
        scale={[7.403, 8.161, 5.563]}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0011.geometry}
        material={materials['PP_Standard_Material.012']}
        position={[-206.815, -4.259, 118.177]}
        rotation={[0, 1.407, 0]}
        scale={5.786}
      />
      <mesh
        geometry={nodes.PP_Forest_Mountain_Moss_01_001_PP_Standard_Material_0012.geometry}
        material={materials['PP_Standard_Material.013']}
        position={[235.087, -4.259, -90.544]}
        rotation={[-0.001, 1.407, 0]}
        scale={[7.898, 8.592, 6.187]}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.014']}
        position={[-19.325, -3.616, 35.683]}
        scale={4.039}
      />
      <mesh
        geometry={nodes.PP_Tree_10_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.015']}
        position={[-17.693, -1.605, 43.544]}
        rotation={[-Math.PI, 1.137, -Math.PI]}
        scale={2.271}
      />
      <mesh
        geometry={nodes.PP_Tree_10_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.016']}
        position={[-17.949, -1.605, 47.251]}
        rotation={[0, 1.508, 0]}
        scale={1.878}
      />
      <mesh
        geometry={nodes.PP_Rock_Moss_Grown_11_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.017']}
        position={[39.466, -2.068, 49.24]}
        rotation={[0, 1.552, 0]}
        scale={4.265}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.018']}
        position={[4.804, -3.632, 149.564]}
        rotation={[0, 1.365, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.019']}
        position={[-4.96, -3.023, -48.343]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.020']}
        position={[59.624, -3.023, -7.394]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.021']}
        position={[21.973, -3.023, 28.883]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0004.geometry}
        material={materials['PP_Standard_Material.022']}
        position={[-86.584, -3.023, 10.085]}
        rotation={[Math.PI, -0.926, Math.PI]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0005.geometry}
        material={materials['PP_Standard_Material.023']}
        position={[103.596, -3.023, 29.982]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0006.geometry}
        material={materials['PP_Standard_Material.024']}
        position={[-49.757, -3.023, -55.488]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0007.geometry}
        material={materials['PP_Standard_Material.025']}
        position={[-60.2, -3.023, 78.077]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.026']}
        position={[93.408, -3.632, 93.114]}
        rotation={[-Math.PI, 0.125, -Math.PI]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Rock_Moss_Grown_11_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.027']}
        position={[17.48, -2.068, 110.8]}
        rotation={[0, 1.552, 0]}
        scale={4.265}
      />
      <mesh
        geometry={nodes.PP_Rock_Moss_Grown_11_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.028']}
        position={[-105.917, -2.068, 114.923]}
        rotation={[0, 0.733, 0]}
        scale={4.265}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0004.geometry}
        material={materials['PP_Standard_Material.029']}
        position={[-91.275, -3.632, 115.925]}
        rotation={[0, -0.233, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0005.geometry}
        material={materials['PP_Standard_Material.030']}
        position={[24.592, -3.632, 133.404]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0006.geometry}
        material={materials['PP_Standard_Material.031']}
        position={[20.634, -3.632, 147.915]}
        rotation={[0, 0.253, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0007.geometry}
        material={materials['PP_Standard_Material.032']}
        position={[63.507, -3.632, 137.691]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0008.geometry}
        material={materials['PP_Standard_Material.033']}
        position={[103.082, -3.632, 79.978]}
        rotation={[0, 0.806, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0009.geometry}
        material={materials['PP_Standard_Material.034']}
        position={[-143.931, -3.632, 45.02]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0010.geometry}
        material={materials['PP_Standard_Material.035']}
        position={[50.975, -3.632, 147.255]}
        rotation={[-Math.PI, 1.535, -Math.PI]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0011.geometry}
        material={materials['PP_Standard_Material.036']}
        position={[73.401, -3.632, 126.478]}
        rotation={[0, -0.353, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0012.geometry}
        material={materials['PP_Standard_Material.037']}
        position={[20.634, -3.632, 121.861]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0013.geometry}
        material={materials['PP_Standard_Material.038']}
        position={[-47.632, -3.632, 78.988]}
        rotation={[-Math.PI, 1.501, -Math.PI]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0014.geometry}
        material={materials['PP_Standard_Material.039']}
        position={[34.156, -3.632, 123.84]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0015.geometry}
        material={materials['PP_Standard_Material.040']}
        position={[-0.143, -3.632, 128.787]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0016.geometry}
        material={materials['PP_Standard_Material.041']}
        position={[-137.336, -3.632, 61.509]}
        rotation={[0, 0.64, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.042']}
        position={[-117.566, -3.023, -28.239]}
        scale={6.608}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.043']}
        position={[-85.906, -3.023, 54.868]}
        rotation={[0, 0.976, 0]}
        scale={5.021}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.044']}
        position={[15.339, -3.023, 133.358]}
        scale={4.205}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0004.geometry}
        material={materials['PP_Standard_Material.045']}
        position={[41.063, -3.023, 108.294]}
        scale={5.022}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0005.geometry}
        material={materials['PP_Standard_Material.046']}
        position={[-44.023, -3.023, 145.231]}
        scale={2.463}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0006.geometry}
        material={materials['PP_Standard_Material.047']}
        position={[-5.437, -3.023, 115.22]}
        scale={4.178}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0007.geometry}
        material={materials['PP_Standard_Material.048']}
        position={[-92.832, -3.023, 29.144]}
        rotation={[0, -1.467, 0]}
        scale={5.391}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0008.geometry}
        material={materials['PP_Standard_Material.049']}
        position={[51.946, -3.023, 51.24]}
        rotation={[0, -0.851, 0]}
        scale={6.608}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0009.geometry}
        material={materials['PP_Standard_Material.050']}
        position={[-138.343, -3.023, -3.835]}
        scale={5.548}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0010.geometry}
        material={materials['PP_Standard_Material.051']}
        position={[-143.62, -3.023, 28.485]}
        rotation={[0, -1.059, 0]}
        scale={5.884}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_06_001_PP_Standard_Material_0011.geometry}
        material={materials['PP_Standard_Material.052']}
        position={[-68.757, -3.023, 128.081]}
        scale={2.509}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0008.geometry}
        material={materials['PP_Standard_Material.053']}
        position={[-28.211, -3.023, 126.831]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0009.geometry}
        material={materials['PP_Standard_Material.054']}
        position={[-95.488, -3.023, -38.065]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0010.geometry}
        material={materials['PP_Standard_Material.055']}
        position={[-83.945, -3.023, 147.938]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0011.geometry}
        material={materials['PP_Standard_Material.056']}
        position={[-16.668, -3.023, 143.32]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0012.geometry}
        material={materials['PP_Standard_Material.057']}
        position={[-84.275, -3.023, -49.937]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Birch_Tree_05_001_PP_Standard_Material_0013.geometry}
        material={materials['PP_Standard_Material.058']}
        position={[67.099, -3.023, 106.054]}
        scale={3.348}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0017.geometry}
        material={materials['PP_Standard_Material.059']}
        position={[-71.707, -3.632, -50.949]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0018.geometry}
        material={materials['PP_Standard_Material.060']}
        position={[-93.473, -3.632, 129.446]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0019.geometry}
        material={materials['PP_Standard_Material.061']}
        position={[-121.506, -3.632, 83.935]}
        rotation={[-Math.PI, 1.47, -Math.PI]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0020.geometry}
        material={materials['PP_Standard_Material.062']}
        position={[-25.866, -3.632, -52.598]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0021.geometry}
        material={materials['PP_Standard_Material.063']}
        position={[104.731, -3.632, 41.392]}
        rotation={[0, 1.074, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Tree_02_001_PP_Standard_Material_0022.geometry}
        material={materials['PP_Standard_Material.064']}
        position={[22.613, -3.632, 36.115]}
        rotation={[0, 1.175, 0]}
        scale={5.511}
      />
      <mesh
        geometry={nodes.PP_Rock_Pile_Forest_Moss_10_001_PP_Standard_Material_0001.geometry}
        material={materials['PP_Standard_Material.065']}
        position={[-30.447, -6.232, 32.98]}
        rotation={[0, 1.326, 0]}
        scale={3.819}
      />
      <mesh
        geometry={nodes.PP_Rock_Pile_Forest_Moss_10_001_PP_Standard_Material_0002.geometry}
        material={materials['PP_Standard_Material.066']}
        position={[-60.788, -6.232, 140.162]}
        rotation={[-Math.PI, 0.561, -Math.PI]}
        scale={3.533}
      />
      <mesh
        geometry={nodes.PP_Rock_Pile_Forest_Moss_10_001_PP_Standard_Material_0003.geometry}
        material={materials['PP_Standard_Material.067']}
        position={[-32.096, -6.232, 138.184]}
        rotation={[-Math.PI, 0.561, -Math.PI]}
        scale={3.047}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Material.004']}
        position={[0, 0.45, 0]}
        scale={[1.461, 1, 0.386]}
      />
    </group>
  )
}

export default RaceTrack
