/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Oscar R (https://sketchfab.com/braidoner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-low-poly-hoth-skybox-caddf0ec811a47d5a2449a4d076a9d7b
Title: Star Wars - Low Poly Hoth Skybox
*/

import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import skyScene from '/assets/3d/sky.glb'


const Sky = ({ ...props }) => {
    const skyRef = useRef();

    const { nodes, materials } = useGLTF(skyScene)

    useFrame(({ clock }) => {
        skyRef.current.rotation.y += (clock.getElapsedTime()) / (clock.getElapsedTime()*10000)
      })

    return (
        <a.group ref={skyRef}{...props} scale={1} position={[0,0,0]}>
            <mesh
                geometry={nodes.hoth_sky_lambert1_0.geometry}
                material={materials.lambert1}
                scale={267.253}
            />
            <mesh
                geometry={nodes.cloud17_lambert1_0.geometry}
                material={materials.lambert1}
                position={[204.159, -227.504, 47.945]}
                rotation={[0, -0.283, -3.106]}
                scale={4.082}
            />
            <mesh
                geometry={nodes.cloud18_lambert1_0.geometry}
                material={materials.lambert1}
                position={[113.759, 252.834, -176.519]}
                rotation={[-0.06, 0.944, -3.085]}
                scale={4.082}
            />
            <mesh geometry={nodes.clouds2_lambert1_0.geometry} material={materials.lambert1} />
        </a.group>
    )
}

export default Sky;
